config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/help' => 'static_pages#help'
  get    '/about' => 'static_pages#about'
  get    '/contact' => 'static_pages#contact'
  get    '/signup' => 'users#new'
  post '/signup'  => 'users#create'
  patch "/users/:id/edit"  => 'users#update'
  get "/users/oauth" => 'users#oauth'
  get "/users/callback" => 'users#callback'
  get    '/login' => 'sessions#new'
  post   '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  post "/users/:id" => 'records#create'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :records,          only: [:destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :records, -> {order("created_at DESC")}, dependent: :destroy
  before_save :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: {maximum: 20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 100},
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: true
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  has_secure_password
  attr_accessor :remember_token, :activation_token, :reset_token



  def new
    @user = User.new
  end


  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(self.activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    @record = current_user.records.build
    @records = @user.records.page(params[:page]).per(7)

    if params[:duration] == "all"
      @graph_weights = @user.records.pluck(:weight)
      @graph_date = @user.records.pluck(:created_at).map{|date| date.strftime("%-m/%-d %k:%M")}
    elsif params[:duration] == "month"
      from = Time.zone.now - 720.hour
      to = Time.zone.now
      @graph_weights = @user.records.where(created_at: from..to).pluck(:weight)
      @graph_date = @user.records.where(created_at: from..to).pluck(:created_at).map{|date| date.strftime("%-m/%-d %k:%M")}
    elsif params[:duration] == "week"
      from = Time.zone.now - 168.hour
      to = Time.zone.now
      @graph_weights = @user.records.where(created_at: from..to).pluck(:weight)
      @graph_date = @user.records.where(created_at: from..to).pluck(:created_at).map{|date| date.strftime("%-m/%-d %k:%M")}
    else
      from = Time.zone.now - 72.hour
      to = Time.zone.now
      @graph_weights = @user.records.where(created_at: from..to).pluck(:weight)
      @graph_date = @user.records.where(created_at: from..to).pluck(:created_at).map{|date| date.strftime("%-m/%-d %k:%M")}
    end

    @graph_weights.reverse!
    @graph_date.reverse!
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    flash[:succes] = "The user was deleted"
    redirect_to login_url
  end

  def oauth
    client = OAuth2::Client.new(ENV["API_ID"], ENV["API_SECRET"], :site => 'https://www.healthplanet.jp', :authorize_url => ' https://www.healthplanet.jp/oauth/auth',
              :token_url => 'https://www.healthplanet.jp/oauth/token')
    redirect_uri = 'https://body-w.herokuapp.com/users/callback'
    authorize_url = "https://www.healthplanet.jp/oauth/auth?client_id=#{ENV["API_ID"]}&redirect_uri=#{redirect_uri}&scope=innerscan&response_type=code"
    redirect_to authorize_url
  end

  def callback
    client = OAuth2::Client.new(ENV["API_ID"], ENV["API_SECRET"],
    {
      site: 'https://www.healthplanet.jp/',
      token_url: 'oauth/token',
    }
    )
    token = client.auth_code.get_token(
    params[:code],
    {:redirect_uri => 'https://body-w.herokuapp.com/users/callback',
    :grant_type => "authorization_code"}
    )

    access_token = token.token
    refresh_token = token.refresh_token

    secret = ENV['SECRET']
    encryptor = ::ActiveSupport::MessageEncryptor.new(secret, cipher: 'aes-256-cbc')
    encrypt_access_token = encryptor.encrypt_and_sign(access_token)
    encrypt_refresh_token = encryptor.encrypt_and_sign(refresh_token)
    current_user.update_attributes(access_token: encrypt_access_token, refresh_token: encrypt_refresh_token)

    redirect_to "/users/#{current_user.id}"
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end


    def correct_user
      @user = User.find_by(id: params[:id])
      unless current_user?(@user)
        flash[:danger] = "You are not authenticated"
        redirect_to(root_url)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_form.html.erb
<div class="col-sm-6 offset-sm-3" >
  <%= form_for(@user, url: yield(:url)) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation%>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/_graph.html.erb
<div class="chart_container"><canvas id="myChart" height="330" width="650"></canvas></div>

<script>
var ctx = document.getElementById("myChart").getContext('2d');
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels:  <%= raw @graph_date %> ,
        datasets: [{
            label: "weight",
            pointHitRadius:10,
            pointBorderColor: "white",
            data: <%= raw @graph_weights %>,
            lineTension: 0.05,
            backgroundColor: 'rgba(0, 123, 255, 1.0)',
            borderColor: 'rgba(0, 123, 255, 1.0)',
            fill: false,
            pointRadius:3.5,
            pointHoverRadius: 5
        }]
    },
    options: {
      scales: {
            yAxes: [
        {
          ticks: {
            <% if  @graph_weights.length < 1  %>
              min:0
            <% else %>
              suggestedMin: <%=  @graph_weights.min - 1%>,
              suggestedMax: <%=  @graph_weights.max + 1%>
            <% end %>
          }
        }
      ]
    },
      responsive: true,
      maintainAspectRatio: false,
      legend: {
                display: false,

            },
      chartArea: {
        backgroundColor: 'black',
    }
       }
});
</script>

app/views/users/_period_tabs.html.erb
<ul class="buttons-ul">
   <li><a class="btn btn-outline-primary btn-block <%= "active" if params[:duration] != "week" && params[:duration] != "month" && params[:duration] != "all" %>" href= <%= "/users/#{@user.id}?duration=3days#{"&page=#{params[:page]}" if params[:page] != nil }" %> role="button">3days</a></li>
   <li><a class="btn btn-outline-primary btn-block <%= "active" if params[:duration] == "week" %>" href= <%= "/users/#{@user.id}?duration=week#{"&page=#{params[:page]}" if params[:page] != nil }" %> role="button">Week</a></li>
   <li><a class="btn btn-outline-primary btn-block <%= "active" if params[:duration] == "month" %>"  href= <%= "/users/#{@user.id}?duration=month#{"&page=#{params[:page]}" if params[:page] != nil }" %> role="button">Month</a></li>
   <li><a class="btn btn-outline-primary btn-block <%= "active" if params[:duration] == "all" %>"  href= <%= "/users/#{@user.id}?duration=all#{"&page=#{params[:page]}" if params[:page] != nil }" %> role="button">All</a></li>
</ul>

app/views/users/_record_form.html.erb
<div class="col-sm-6 offset-sm-3" >
  <%= form_for(@record, url: "/users/#{@user.id}#{"?duration=#{params[:duration]}" if params[:duration] != nil }#{"&page=#{params[:page]}" if params[:duration] != nil && params[:page] != nil }#{"?page=#{params[:page]}" if params[:duration] == nil && params[:page] != nil }") do |f| %>



    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group record-form">
      <%= f.number_field :weight, placeholder: "Input weight...", class: "form-control", step: 0.01  %>
    </div>

    <%= f.submit "Save" %>
  <% end %>
</div>

app/views/users/_table.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Date</th>
    <th>Weight</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
  <% @records.each do |record| %>
    <tr>
      <td><%= record.created_at.strftime('%Y-%m-%d %H:%M') %></td>
      <td><%= record.weight %> kg</td>
        <td>
          <a rel="nofollow" data-method="delete" href= <%= "/records/#{record.id}" %>>Delete</a>
        </td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="pagewarapper">
   <%= paginate @records %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:url, edit_user_path(@user)) %>
<% provide(:button_text, "Save changes") %>


<h1 class="page-title">Update your profile</h1>

<div class="row">
    <%= render "form" %>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<% provide(:url, signup_path) %>
<% provide(:button_text, "Create account") %>

<h1 class="page-title">Sign up</h1>
<div class="container">
  <div class="signup-form">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<%= render 'users/record_form' %>

<%= render 'users/period_tabs' %>

<%= render 'users/graph' %>

<%= render 'users/table' %>